FEATURE: WA-12423 Added new models for AccessLog API
gooddata/gooddata-java pull request #1001
Opened 2021-02-25 15:57 UTC by jeskepetr

2021-02-25 15:57 UTC, gdgate commented
Build succeeded (check pipeline).

2021-02-26 07:04 UTC, peter-plochan commented
Please do not use GoodData internal tickets in PRs/commits for this "really public" OSS library. Create [GitHub issue](https://github.com/gooddata/gooddata-java/issues) instead and add there the description of problem/feature and possibly, if you need to, link the internal ticket within this issue.

2021-02-26 11:30 UTC, peter-plochan requested changes
See comments below.
Also, I'm just wondering what's the purpose of this not-[AuditEvent](https://github.com/gooddata/gooddata-java/blob/b6f15692d3aca46c84c22c83bc7c227ff4537b2b/gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AuditEvent.java#L26) bean and its special API endpoint? As I can see, it still represents a part audit log (GD internally - CFAL)...

2021-02-26 11:30 UTC, peter-plochan commented on gooddata-java/src/main/java/com/gooddata/sdk/service/accesslog/TimeFilterPageRequest.java
> +public class TimeFilterPageRequest extends CustomPageRequest {
Also, what's the purpose of this class when it is not used in any GoodData service (meaning the service within this library, usually inheritor of [AbstractService](https://github.com/gooddata/gooddata-java/blob/ac293f03758a0b9081dd1c7ef25d67090caff3ab/gooddata-java/src/main/java/com/gooddata/sdk/service/AbstractService.java))?

2021-02-26 11:48 UTC, mverbovsky commented
> See comments below.
> Also, I'm just wondering what's the purpose of this not-[AuditEvent](https://github.com/gooddata/gooddata-java/blob/b6f15692d3aca46c84c22c83bc7c227ff4537b2b/gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AuditEvent.java#L26) bean and its special API endpoint? As I can see, it still represents a part audit log (GD internally - CFAL)...

It is part of cfal, but they are special events directly from haproxy that represents access logs for particular hosts. In this case you do not have domain and user context. So if you try to reuse AuditLog then you will have to change whole logic behind AuditLogs because they are build upon domain and user.

2021-02-26 11:58 UTC, peter-plochan commented
> > See comments below.
> > Also, I'm just wondering what's the purpose of this not-[AuditEvent](https://github.com/gooddata/gooddata-java/blob/b6f15692d3aca46c84c22c83bc7c227ff4537b2b/gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AuditEvent.java#L26) bean and its special API endpoint? As I can see, it still represents a part audit log (GD internally - CFAL)...
> 
> @peter-plochan It is part of cfal, but they are special events/acces logs directly from haproxy that represents access logs for particular hosts. In this case you do not have domain and user context. So if you try to reuse AuditLog then you will have to change whole logic behind AuditLogs because they are build upon domain and user. The API also will support Common Log Format, so it is really access logs to particular host.

Ahh, ok, thanks for the explanation @mverbovsky 

So the question is, if this whole thing should or should not share the Java package with the other audit log entities (`AuditEvent`).

2021-02-26 13:46 UTC, mverbovsky commented
> > > See comments below.
> > > Also, I'm just wondering what's the purpose of this not-[AuditEvent](https://github.com/gooddata/gooddata-java/blob/b6f15692d3aca46c84c22c83bc7c227ff4537b2b/gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AuditEvent.java#L26) bean and its special API endpoint? As I can see, it still represents a part audit log (GD internally - CFAL)...
> > 
> > 
> > @peter-plochan It is part of cfal, but they are special events/acces logs directly from haproxy that represents access logs for particular hosts. In this case you do not have domain and user context. So if you try to reuse AuditLog then you will have to change whole logic behind AuditLogs because they are build upon domain and user. The API also will support Common Log Format, so it is really access logs to particular host.
> 
> Ahh, ok, thanks for the explanation @mverbovsky
> 
> So the question is, if this whole thing should or should not share the Java package with the other audit log entities (`AuditEvent`).

I would vote for the same package, because it is still part of audit logging.

2021-03-02 17:19 UTC, gdgate commented
Build succeeded (check pipeline).

2021-03-02 17:30 UTC, gdgate commented
Build succeeded (check pipeline).

2021-03-02 17:36 UTC, jeskepetr commented on gooddata-java/src/main/java/com/gooddata/sdk/service/accesslog/TimeFilterPageRequest.java
> +        copy.setLimit(this.getSanitizedLimit() + 1);
I am not entirely sure if it is better now when I've rewritten it. Please have a look if I've reimplemented as you've imagined.

2021-03-03 06:59 UTC, peter-plochan commented on gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AccessLog.java
> + * Model class, used for special cfal events/access logs directly from haproxy,
```suggestion
 * Model class, used for special audit log events/access logs directly from haproxy,
```

2021-03-03 07:06 UTC, peter-plochan commented on gooddata-java/src/main/java/com/gooddata/sdk/service/accesslog/TimeFilterPageRequest.java
> +        copy.setLimit(this.getSanitizedLimit() + 1);
ok, you're right, I didn't realise that we need to use the `copy` method from the `AuditEventPageRequest`, so the previous one was better

2021-03-03 08:25 UTC, gdgate commented
Build succeeded (check pipeline).

2021-03-03 08:29 UTC, gdgate commented
Build succeeded (check pipeline).

2021-03-03 09:02 UTC, peter-plochan approved these changes
LGTM 👍

2021-03-03 09:03 UTC, merged

2021-03-03 09:03 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/213/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-fossa-scanning-zuul-el7/53/ : SUCCESS in 21s (non-voting)